### ISSUE TITLE
can this script export the groups that i'm in(while not Administrated by me)?

### ISSUE THREAD

**Issue by roger125** [acocciolo/facebook_page_and_group_photo_exporter#1]
Hi Author,
   as the subject, can this script export the photos of facebook groups that i'm in(while not Administrated by me)?
  thanks.

**Comment by acocciolo** [comment]
Hi,

It will allow you to export photos from Pages that you like (don't need to be the administrator); however, for Groups you have to be an administrator to export the photos. 

Best,
Anthony
